# Generated by Django 5.2.9 on 2025-12-09 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('sensor_id', models.CharField(max_length=100)),
                ('soil_moisture', models.FloatField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_id', 'timestamp'], name='analytics_s_sensor__75559e_idx')],
            },
        ),
    ]
